function editSeedHotSauceData(arr) {
  for (let i in arr) {
    arr[i].price = Number(arr[i].price.toString().slice(0, -2) + "00");
  }
  return arr;
}

console.log(
  editSeedHotSauceData([
    {
      name: "Maury Menelaws",
      heatLevel: 10,
      price: 4995,
      stock: 880,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "911599410",
      description: "Praesent id massa id nisl venenatis lacinia.",
    },
    {
      name: "Eirena Fiddian",
      heatLevel: 3,
      price: 1834,
      stock: 474,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "850009839",
      description:
        "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.",
    },
    {
      name: "Thornie Halwill",
      heatLevel: 2,
      price: 3670,
      stock: 280,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "647813910",
      description:
        "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.",
    },
    {
      name: "Averil Randalston",
      heatLevel: 5,
      price: 3329,
      stock: 754,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "417108980",
      description:
        "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.",
    },
    {
      name: "Matelda Corkel",
      heatLevel: 10,
      price: 1152,
      stock: 399,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "858800429",
      description: "In congue.",
    },
    {
      name: "Marna Fairburn",
      heatLevel: 6,
      price: 4002,
      stock: 822,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "006977063",
      description:
        "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.",
    },
    {
      name: "Madelena Langstrath",
      heatLevel: 7,
      price: 4813,
      stock: 969,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "087178343",
      description: "Fusce consequat.",
    },
    {
      name: "Tamarah Cote",
      heatLevel: 3,
      price: 2723,
      stock: 839,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "825533378",
      description:
        "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.",
    },
    {
      name: "Adelbert Hogbourne",
      heatLevel: 5,
      price: 2902,
      stock: 670,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "646317222",
      description: "Suspendisse accumsan tortor quis turpis.",
    },
    {
      name: "Justinn Shalliker",
      heatLevel: 10,
      price: 866,
      stock: 893,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "652657878",
      description: "Aliquam erat volutpat. In congue.",
    },
    {
      name: "Leonhard Cannop",
      heatLevel: 7,
      price: 4155,
      stock: 835,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "893616693",
      description:
        "Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.",
    },
    {
      name: "Jorrie Batie",
      heatLevel: 5,
      price: 4830,
      stock: 150,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "099014446",
      description:
        "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    },
    {
      name: "Isabeau Drieu",
      heatLevel: 4,
      price: 4201,
      stock: 297,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "017621516",
      description:
        "Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    },
    {
      name: "Louis Mauvin",
      heatLevel: 3,
      price: 1583,
      stock: 986,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "727760835",
      description:
        "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.",
    },
    {
      name: "Lurleen Nisbet",
      heatLevel: 9,
      price: 586,
      stock: 401,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "916972629",
      description: "Vestibulum ac est lacinia nisi venenatis tristique.",
    },
    {
      name: "Colver Rae",
      heatLevel: 3,
      price: 3467,
      stock: 147,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "761897929",
      description:
        "Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    },
    {
      name: "Jess Merrisson",
      heatLevel: 6,
      price: 604,
      stock: 25,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "069841245",
      description: "Nulla nisl. Nunc nisl.",
    },
    {
      name: "Alvie Henrichsen",
      heatLevel: 9,
      price: 1288,
      stock: 956,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "581094811",
      description:
        "Etiam pretium iaculis justo. In hac habitasse platea dictumst.",
    },
    {
      name: "Towny Blancowe",
      heatLevel: 6,
      price: 3149,
      stock: 689,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "627154520",
      description:
        "Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.",
    },
    {
      name: "Lebbie Collingridge",
      heatLevel: 4,
      price: 3283,
      stock: 99,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "686276137",
      description: "Mauris lacinia sapien quis libero.",
    },
    {
      name: "Gottfried Dorey",
      heatLevel: 2,
      price: 2929,
      stock: 927,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "712076374",
      description: "Donec posuere metus vitae ipsum.",
    },
    {
      name: "Berne O'Brollachain",
      heatLevel: 5,
      price: 4285,
      stock: 450,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "688324932",
      description:
        "Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.",
    },
    {
      name: "Morse Steptow",
      heatLevel: 7,
      price: 4645,
      stock: 610,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "213692902",
      description:
        "Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.",
    },
    {
      name: "Avictor Lghan",
      heatLevel: 8,
      price: 3203,
      stock: 793,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "851970326",
      description: "Maecenas pulvinar lobortis est.",
    },
    {
      name: "Chaddie Cadle",
      heatLevel: 5,
      price: 1881,
      stock: 610,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "661342176",
      description: "Morbi ut odio.",
    },
    {
      name: "Cissiee Christopher",
      heatLevel: 10,
      price: 469,
      stock: 467,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "877471571",
      description:
        "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.",
    },
    {
      name: "Korrie Paskell",
      heatLevel: 6,
      price: 2656,
      stock: 641,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "919357552",
      description: "Morbi quis tortor id nulla ultrices aliquet.",
    },
    {
      name: "De witt Boyles",
      heatLevel: 9,
      price: 2844,
      stock: 282,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "442334899",
      description:
        "Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    },
    {
      name: "Delbert Stutte",
      heatLevel: 9,
      price: 399,
      stock: 154,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "701353547",
      description:
        "Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    },
    {
      name: "Burg Draco",
      heatLevel: 4,
      price: 3013,
      stock: 291,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "739352616",
      description: "Fusce consequat. Nulla nisl.",
    },
    {
      name: "Rubetta Grewcock",
      heatLevel: 5,
      price: 3353,
      stock: 350,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "000880038",
      description:
        "Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
    },
    {
      name: "Agnesse Scrivinor",
      heatLevel: 5,
      price: 2860,
      stock: 5,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "544035341",
      description: "In eleifend quam a odio. In hac habitasse platea dictumst.",
    },
    {
      name: "Aloysius Lodwick",
      heatLevel: 2,
      price: 1744,
      stock: 820,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "578148474",
      description: "Praesent blandit. Nam nulla.",
    },
    {
      name: "Carolyne Barrick",
      heatLevel: 1,
      price: 245,
      stock: 173,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "337379576",
      description:
        "Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.",
    },
    {
      name: "Rourke Rowbotham",
      heatLevel: 3,
      price: 830,
      stock: 120,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "121596160",
      description:
        "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.",
    },
    {
      name: "Feodora Pedrocchi",
      heatLevel: 9,
      price: 3378,
      stock: 919,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "360205096",
      description: "Nulla tempus.",
    },
    {
      name: "Bendite Hallwood",
      heatLevel: 9,
      price: 2537,
      stock: 751,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "628209184",
      description: "Nulla facilisi. Cras non velit nec nisi vulputate nonummy.",
    },
    {
      name: "Florian Mapham",
      heatLevel: 3,
      price: 3860,
      stock: 347,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "316536241",
      description:
        "Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.",
    },
    {
      name: "Phillie Mackness",
      heatLevel: 6,
      price: 1448,
      stock: 300,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "646192503",
      description:
        "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.",
    },
    {
      name: "Lindsay Isakovic",
      heatLevel: 2,
      price: 2725,
      stock: 904,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "775283396",
      description: "Nunc purus. Phasellus in felis.",
    },
    {
      name: "Erhard Rumbellow",
      heatLevel: 2,
      price: 182,
      stock: 367,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "012577907",
      description: "Integer tincidunt ante vel ipsum.",
    },
    {
      name: "Angel Chappelow",
      heatLevel: 8,
      price: 3789,
      stock: 353,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "991018226",
      description:
        "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.",
    },
    {
      name: "Hollie Treleven",
      heatLevel: 3,
      price: 2885,
      stock: 281,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "679133193",
      description: "Fusce posuere felis sed lacus.",
    },
    {
      name: "Roxie Nisius",
      heatLevel: 7,
      price: 2446,
      stock: 946,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "978941330",
      description: "Duis mattis egestas metus. Aenean fermentum.",
    },
    {
      name: "Rodi Vasyukhin",
      heatLevel: 7,
      price: 1917,
      stock: 644,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "626759634",
      description: "In hac habitasse platea dictumst.",
    },
    {
      name: "Hube Marsland",
      heatLevel: 7,
      price: 427,
      stock: 343,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "477984540",
      description:
        "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.",
    },
    {
      name: "Idell Satchel",
      heatLevel: 3,
      price: 3565,
      stock: 580,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "980166317",
      description: "Etiam vel augue.",
    },
    {
      name: "Ulla Worham",
      heatLevel: 7,
      price: 2064,
      stock: 53,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "703553064",
      description:
        "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.",
    },
    {
      name: "Wanids Pealing",
      heatLevel: 6,
      price: 650,
      stock: 693,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "586962753",
      description:
        "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.",
    },
    {
      name: "Peg Cuddehay",
      heatLevel: 3,
      price: 2322,
      stock: 14,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "234945943",
      description: "Suspendisse potenti.",
    },
    {
      name: "Danyelle Joselevitch",
      heatLevel: 2,
      price: 3203,
      stock: 260,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "899197700",
      description:
        "In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    },
    {
      name: "Cherilyn Saban",
      heatLevel: 4,
      price: 3626,
      stock: 666,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "814816283",
      description: "In eleifend quam a odio.",
    },
    {
      name: "Jo Crebbin",
      heatLevel: 5,
      price: 1363,
      stock: 566,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "476119821",
      description: "Duis mattis egestas metus. Aenean fermentum.",
    },
    {
      name: "Loutitia Desporte",
      heatLevel: 4,
      price: 2796,
      stock: 224,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "226412937",
      description:
        "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.",
    },
    {
      name: "Legra Drakard",
      heatLevel: 9,
      price: 4197,
      stock: 765,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "803224910",
      description: "Nulla facilisi.",
    },
    {
      name: "Regina Bogie",
      heatLevel: 10,
      price: 3222,
      stock: 862,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "542208969",
      description:
        "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.",
    },
    {
      name: "Innis Stocking",
      heatLevel: 10,
      price: 4627,
      stock: 120,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "355751678",
      description:
        "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.",
    },
    {
      name: "Ange Southerden",
      heatLevel: 1,
      price: 1831,
      stock: 869,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "886984379",
      description: "Integer ac leo. Pellentesque ultrices mattis odio.",
    },
    {
      name: "Karee Dugmore",
      heatLevel: 1,
      price: 3140,
      stock: 898,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "549336738",
      description:
        "Etiam pretium iaculis justo. In hac habitasse platea dictumst.",
    },
    {
      name: "Jim Djokovic",
      heatLevel: 7,
      price: 1376,
      stock: 164,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "014913599",
      description: "Nullam porttitor lacus at turpis.",
    },
    {
      name: "Stoddard Lockwood",
      heatLevel: 9,
      price: 1512,
      stock: 591,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "814363577",
      description:
        "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.",
    },
    {
      name: "Viki Sutter",
      heatLevel: 9,
      price: 2694,
      stock: 896,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "150088479",
      description: "Ut at dolor quis odio consequat varius. Integer ac leo.",
    },
    {
      name: "Deanna Perazzo",
      heatLevel: 8,
      price: 2477,
      stock: 344,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "453256368",
      description: "Donec posuere metus vitae ipsum.",
    },
    {
      name: "Roscoe Mulvy",
      heatLevel: 5,
      price: 3901,
      stock: 162,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "744295591",
      description:
        "Aenean fermentum. Donec ut mauris eget massa tempor convallis.",
    },
    {
      name: "Thurston Upjohn",
      heatLevel: 1,
      price: 534,
      stock: 661,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "002079981",
      description: "Morbi non quam nec dui luctus rutrum.",
    },
    {
      name: "Terry Elphee",
      heatLevel: 10,
      price: 4761,
      stock: 792,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "287982786",
      description:
        "Etiam pretium iaculis justo. In hac habitasse platea dictumst.",
    },
    {
      name: "Seth Nottram",
      heatLevel: 4,
      price: 969,
      stock: 407,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "692539487",
      description:
        "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.",
    },
    {
      name: "Stephanie Faucett",
      heatLevel: 3,
      price: 938,
      stock: 146,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "912922147",
      description:
        "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.",
    },
    {
      name: "Sibby Downes",
      heatLevel: 2,
      price: 1863,
      stock: 157,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "690287967",
      description:
        "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.",
    },
    {
      name: "Emelyne Henrichsen",
      heatLevel: 2,
      price: 2243,
      stock: 907,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "421356707",
      description:
        "Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    },
    {
      name: "Mei Marrett",
      heatLevel: 9,
      price: 385,
      stock: 257,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "851857576",
      description: "Aenean sit amet justo. Morbi ut odio.",
    },
    {
      name: "Corena Keneforde",
      heatLevel: 10,
      price: 2951,
      stock: 766,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "307828597",
      description:
        "Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.",
    },
    {
      name: "Kippy Heyfield",
      heatLevel: 2,
      price: 1225,
      stock: 89,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "278891964",
      description: "Vestibulum ac est lacinia nisi venenatis tristique.",
    },
    {
      name: "Padriac Bosket",
      heatLevel: 4,
      price: 946,
      stock: 736,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "589312341",
      description: "Aenean fermentum.",
    },
    {
      name: "Saul Bumphrey",
      heatLevel: 1,
      price: 1156,
      stock: 906,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "766257472",
      description:
        "Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    },
    {
      name: "Deane Broseke",
      heatLevel: 7,
      price: 518,
      stock: 701,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "090249205",
      description:
        "Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.",
    },
    {
      name: "Alonzo Kluge",
      heatLevel: 4,
      price: 2222,
      stock: 811,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "506478163",
      description: "Phasellus id sapien in sapien iaculis congue.",
    },
    {
      name: "Gilbertine Alleburton",
      heatLevel: 9,
      price: 3788,
      stock: 654,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "091825972",
      description: "Mauris ullamcorper purus sit amet nulla.",
    },
    {
      name: "Shel MacMeanma",
      heatLevel: 5,
      price: 1002,
      stock: 175,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "171706990",
      description:
        "Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    },
    {
      name: "Marlene Brister",
      heatLevel: 4,
      price: 430,
      stock: 119,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "465568761",
      description:
        "Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.",
    },
    {
      name: "Giorgi Parsell",
      heatLevel: 2,
      price: 171,
      stock: 863,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "115492199",
      description:
        "Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    },
    {
      name: "Jody Crichmere",
      heatLevel: 10,
      price: 1843,
      stock: 156,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "849804083",
      description:
        "Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.",
    },
    {
      name: "Bria Kilday",
      heatLevel: 8,
      price: 2740,
      stock: 233,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "025584507",
      description:
        "Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    },
    {
      name: "Constantino Attrill",
      heatLevel: 3,
      price: 2226,
      stock: 287,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "232106024",
      description: "Duis ac nibh.",
    },
    {
      name: "Diego Dallman",
      heatLevel: 3,
      price: 3995,
      stock: 720,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "878292911",
      description:
        "Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.",
    },
    {
      name: "Bone Schimon",
      heatLevel: 8,
      price: 2648,
      stock: 694,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "873435147",
      description: "Pellentesque ultrices mattis odio. Donec vitae nisi.",
    },
    {
      name: "Kearney Alaway",
      heatLevel: 7,
      price: 2500,
      stock: 10,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "973332605",
      description:
        "Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.",
    },
    {
      name: "Livvy Rumming",
      heatLevel: 1,
      price: 4507,
      stock: 313,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "355318792",
      description:
        "Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.",
    },
    {
      name: "Birgitta Gobbett",
      heatLevel: 3,
      price: 1871,
      stock: 27,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "248554226",
      description:
        "Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.",
    },
    {
      name: "Stillmann Pierse",
      heatLevel: 6,
      price: 3981,
      stock: 744,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "184936815",
      description:
        "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.",
    },
    {
      name: "Marillin Vanyashin",
      heatLevel: 6,
      price: 3369,
      stock: 882,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "759965496",
      description: "Duis at velit eu est congue elementum.",
    },
    {
      name: "Darnell Dearlove",
      heatLevel: 10,
      price: 4294,
      stock: 414,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "633760427",
      description: "Praesent blandit lacinia erat.",
    },
    {
      name: "Georgette Selwyn",
      heatLevel: 9,
      price: 4473,
      stock: 780,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "212676866",
      description: "Nulla ut erat id mauris vulputate elementum.",
    },
    {
      name: "Hedwig Gibbs",
      heatLevel: 3,
      price: 3292,
      stock: 936,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "393342992",
      description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    },
    {
      name: "Clair Curr",
      heatLevel: 4,
      price: 4074,
      stock: 609,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "035328112",
      description:
        "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.",
    },
    {
      name: "Henderson Drinkhall",
      heatLevel: 5,
      price: 1851,
      stock: 401,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "413220132",
      description:
        "Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    },
    {
      name: "Marleah Tue",
      heatLevel: 5,
      price: 4484,
      stock: 459,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "975891568",
      description: "Maecenas tincidunt lacus at velit.",
    },
    {
      name: "Silvano Tolman",
      heatLevel: 7,
      price: 4132,
      stock: 486,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "041222763",
      description: "Etiam justo. Etiam pretium iaculis justo.",
    },
    {
      name: "Mei Nanetti",
      heatLevel: 1,
      price: 1686,
      stock: 757,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "668639451",
      description:
        "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.",
    },
    {
      name: "Tarah Rowswell",
      heatLevel: 4,
      price: 275,
      stock: 524,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "199624171",
      description:
        "Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    },
    {
      name: "Alric Kruger",
      heatLevel: 2,
      price: 1688,
      stock: 527,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "465400688",
      description:
        "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.",
    },
    {
      name: "Ludovika Thumim",
      heatLevel: 4,
      price: 3124,
      stock: 352,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "367440562",
      description:
        "Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    },
    {
      name: "Colby Javes",
      heatLevel: 3,
      price: 707,
      stock: 951,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "218154675",
      description: "Morbi porttitor lorem id ligula.",
    },
    {
      name: "Blisse Szymoni",
      heatLevel: 1,
      price: 2642,
      stock: 157,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "379527234",
      description: "Nulla tellus. In sagittis dui vel nisl.",
    },
    {
      name: "Joelynn Spurrier",
      heatLevel: 3,
      price: 3634,
      stock: 621,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "798000284",
      description:
        "Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.",
    },
    {
      name: "Fanny Cappell",
      heatLevel: 4,
      price: 3193,
      stock: 426,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "076055949",
      description:
        "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.",
    },
    {
      name: "Isaac McVane",
      heatLevel: 5,
      price: 4994,
      stock: 872,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "589841626",
      description: "Integer ac leo.",
    },
    {
      name: "Janey Worpole",
      heatLevel: 1,
      price: 2654,
      stock: 483,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "462799453",
      description: "Morbi non quam nec dui luctus rutrum.",
    },
    {
      name: "Marilee Mathiasen",
      heatLevel: 6,
      price: 4808,
      stock: 138,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "832638955",
      description:
        "In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    },
    {
      name: "Roberta Stinson",
      heatLevel: 2,
      price: 894,
      stock: 666,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "842474561",
      description: "Donec posuere metus vitae ipsum. Aliquam non mauris.",
    },
    {
      name: "Gilbert Cod",
      heatLevel: 9,
      price: 4266,
      stock: 464,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "003421724",
      description: "Nullam molestie nibh in lectus.",
    },
    {
      name: "Ada Lempenny",
      heatLevel: 8,
      price: 4345,
      stock: 232,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "701286790",
      description: "Aenean sit amet justo.",
    },
    {
      name: "Ezechiel Lantiffe",
      heatLevel: 3,
      price: 2792,
      stock: 762,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "914598794",
      description:
        "Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    },
    {
      name: "Louise Rubenchik",
      heatLevel: 5,
      price: 2635,
      stock: 69,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "414233645",
      description:
        "Duis at velit eu est congue elementum. In hac habitasse platea dictumst.",
    },
    {
      name: "Trudie Mewburn",
      heatLevel: 10,
      price: 2327,
      stock: 999,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "758674421",
      description: "Integer a nibh.",
    },
    {
      name: "Caye Roby",
      heatLevel: 1,
      price: 1851,
      stock: 60,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "191238510",
      description:
        "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.",
    },
    {
      name: "Virgilio Crowder",
      heatLevel: 10,
      price: 1509,
      stock: 313,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "958455240",
      description: "Integer ac neque.",
    },
    {
      name: "Giffie Edwinson",
      heatLevel: 4,
      price: 3191,
      stock: 939,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "348994008",
      description:
        "Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    },
    {
      name: "Jaquenetta Leband",
      heatLevel: 7,
      price: 2020,
      stock: 912,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "011967268",
      description: "Maecenas ut massa quis augue luctus tincidunt.",
    },
    {
      name: "Danyelle Sayton",
      heatLevel: 4,
      price: 2014,
      stock: 826,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "018260107",
      description: "Suspendisse potenti.",
    },
    {
      name: "Vincenz Tarrier",
      heatLevel: 6,
      price: 3650,
      stock: 711,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "732359280",
      description:
        "Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    },
    {
      name: "Glenn Oganesian",
      heatLevel: 10,
      price: 2944,
      stock: 767,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "890144336",
      description: "Morbi a ipsum. Integer a nibh.",
    },
    {
      name: "Michel Drezzer",
      heatLevel: 2,
      price: 472,
      stock: 969,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "057754580",
      description: "Pellentesque at nulla.",
    },
    {
      name: "Blaine Showell",
      heatLevel: 9,
      price: 4051,
      stock: 712,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "875227984",
      description:
        "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.",
    },
    {
      name: "Alisun Frigot",
      heatLevel: 4,
      price: 1172,
      stock: 609,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "669543142",
      description:
        "Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    },
    {
      name: "Dione O'Spellissey",
      heatLevel: 1,
      price: 4471,
      stock: 554,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "813829040",
      description:
        "Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.",
    },
    {
      name: "Viviana Faye",
      heatLevel: 4,
      price: 1906,
      stock: 270,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "648047263",
      description:
        "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.",
    },
    {
      name: "Bartholomew Goldster",
      heatLevel: 1,
      price: 3028,
      stock: 607,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "373371252",
      description: "Nullam molestie nibh in lectus.",
    },
    {
      name: "Holly Routledge",
      heatLevel: 4,
      price: 4155,
      stock: 727,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "290195851",
      description: "Pellentesque at nulla.",
    },
    {
      name: "Clarey Keune",
      heatLevel: 10,
      price: 1948,
      stock: 175,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "177447843",
      description: "Nunc purus. Phasellus in felis.",
    },
    {
      name: "Ernesto Stummeyer",
      heatLevel: 5,
      price: 2760,
      stock: 54,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "661196603",
      description: "Donec posuere metus vitae ipsum. Aliquam non mauris.",
    },
    {
      name: "Riva Shakle",
      heatLevel: 1,
      price: 4728,
      stock: 293,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "163450475",
      description: "Cras in purus eu magna vulputate luctus.",
    },
    {
      name: "Kaja Lampbrecht",
      heatLevel: 7,
      price: 505,
      stock: 663,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "676842742",
      description: "Nunc purus. Phasellus in felis.",
    },
    {
      name: "Leisha Reichhardt",
      heatLevel: 1,
      price: 3792,
      stock: 348,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "353212002",
      description: "Aenean sit amet justo.",
    },
    {
      name: "Florinda Emeline",
      heatLevel: 1,
      price: 2995,
      stock: 142,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "882657091",
      description: "Nunc rhoncus dui vel sem.",
    },
    {
      name: "Glenna Filippyev",
      heatLevel: 3,
      price: 3377,
      stock: 22,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "500885367",
      description:
        "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.",
    },
    {
      name: "Dorolisa Kobel",
      heatLevel: 4,
      price: 4693,
      stock: 993,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "092187619",
      description:
        "Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    },
    {
      name: "Solomon Sprouls",
      heatLevel: 3,
      price: 265,
      stock: 607,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "378542259",
      description: "Duis ac nibh.",
    },
    {
      name: "Archibold Alejandre",
      heatLevel: 8,
      price: 1856,
      stock: 836,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "445393669",
      description: "Morbi a ipsum.",
    },
    {
      name: "Engracia Tapson",
      heatLevel: 2,
      price: 3294,
      stock: 910,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "997071265",
      description:
        "Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
    },
    {
      name: "Catherina Dreng",
      heatLevel: 10,
      price: 330,
      stock: 744,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "672900000",
      description:
        "Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
    },
    {
      name: "Aubrie Rhyme",
      heatLevel: 3,
      price: 880,
      stock: 414,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "871983554",
      description: "Proin eu mi.",
    },
    {
      name: "Elianore Trythall",
      heatLevel: 1,
      price: 1607,
      stock: 310,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "328172222",
      description: "Mauris lacinia sapien quis libero.",
    },
    {
      name: "Dorotea MacCarter",
      heatLevel: 6,
      price: 2779,
      stock: 758,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "976007727",
      description:
        "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.",
    },
    {
      name: "Lyndsey Partington",
      heatLevel: 2,
      price: 4389,
      stock: 387,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "911435432",
      description: "Aliquam quis turpis eget elit sodales scelerisque.",
    },
    {
      name: "Meir Dinnis",
      heatLevel: 6,
      price: 164,
      stock: 384,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "582687237",
      description: "Aenean auctor gravida sem.",
    },
    {
      name: "Gunar Seyffert",
      heatLevel: 2,
      price: 2440,
      stock: 857,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "338784029",
      description: "Ut tellus.",
    },
    {
      name: "Garth Strick",
      heatLevel: 7,
      price: 4649,
      stock: 907,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "266438916",
      description:
        "Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.",
    },
    {
      name: "Effie Enstone",
      heatLevel: 9,
      price: 1451,
      stock: 924,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "481717698",
      description:
        "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.",
    },
    {
      name: "Farica Whereat",
      heatLevel: 3,
      price: 1547,
      stock: 846,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "752406151",
      description: "In sagittis dui vel nisl.",
    },
    {
      name: "Emery Sellick",
      heatLevel: 3,
      price: 3294,
      stock: 787,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "267122349",
      description: "Nullam molestie nibh in lectus.",
    },
    {
      name: "Sascha Gowanson",
      heatLevel: 5,
      price: 4725,
      stock: 210,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "630929362",
      description: "Nam dui.",
    },
    {
      name: "Adolph Stearn",
      heatLevel: 4,
      price: 4315,
      stock: 722,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "924872722",
      description:
        "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.",
    },
    {
      name: "Annabel Nuschke",
      heatLevel: 8,
      price: 2181,
      stock: 635,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "977491214",
      description:
        "Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    },
    {
      name: "Deana Searjeant",
      heatLevel: 9,
      price: 3190,
      stock: 343,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "954450713",
      description:
        "Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.",
    },
    {
      name: "Dane Belson",
      heatLevel: 9,
      price: 1590,
      stock: 395,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "567566442",
      description:
        "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    },
    {
      name: "Gustav Tarry",
      heatLevel: 5,
      price: 965,
      stock: 944,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "345446997",
      description:
        "Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    },
    {
      name: "Martie Vanetti",
      heatLevel: 5,
      price: 895,
      stock: 42,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "344823432",
      description:
        "Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    },
    {
      name: "Lisette Castletine",
      heatLevel: 3,
      price: 3478,
      stock: 94,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "171101034",
      description: "Maecenas pulvinar lobortis est. Phasellus sit amet erat.",
    },
    {
      name: "Hettie Bernli",
      heatLevel: 4,
      price: 3310,
      stock: 655,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "090022160",
      description:
        "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    },
    {
      name: "Darrelle Scoggan",
      heatLevel: 9,
      price: 3666,
      stock: 963,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "834877510",
      description:
        "Etiam pretium iaculis justo. In hac habitasse platea dictumst.",
    },
    {
      name: "Enid Gilderoy",
      heatLevel: 8,
      price: 1543,
      stock: 382,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "109281234",
      description: "Pellentesque viverra pede ac diam.",
    },
    {
      name: "Amalle McManus",
      heatLevel: 10,
      price: 4275,
      stock: 302,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "267390870",
      description: "Donec posuere metus vitae ipsum.",
    },
    {
      name: "Verla Corkell",
      heatLevel: 7,
      price: 4164,
      stock: 300,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "296517676",
      description:
        "Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.",
    },
    {
      name: "Erny Cuddy",
      heatLevel: 5,
      price: 2716,
      stock: 588,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "918739431",
      description:
        "Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.",
    },
    {
      name: "Dacey Rennocks",
      heatLevel: 9,
      price: 887,
      stock: 672,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "752011644",
      description: "Curabitur at ipsum ac tellus semper interdum.",
    },
    {
      name: "Kelvin Hathorn",
      heatLevel: 2,
      price: 4070,
      stock: 1,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "684438863",
      description:
        "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.",
    },
    {
      name: "Jerrold Robken",
      heatLevel: 7,
      price: 4210,
      stock: 656,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "368620567",
      description: "Suspendisse accumsan tortor quis turpis.",
    },
    {
      name: "Ker Fabri",
      heatLevel: 2,
      price: 552,
      stock: 749,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "932963276",
      description: "Donec vitae nisi.",
    },
    {
      name: "Rozalin Seyfart",
      heatLevel: 6,
      price: 931,
      stock: 686,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "098167304",
      description: "Nulla mollis molestie lorem.",
    },
    {
      name: "Minne Busk",
      heatLevel: 8,
      price: 2875,
      stock: 466,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "586747357",
      description:
        "Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    },
    {
      name: "Laney Oldacre",
      heatLevel: 9,
      price: 4665,
      stock: 449,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "973643307",
      description: "Aliquam erat volutpat.",
    },
    {
      name: "Hamil Plait",
      heatLevel: 7,
      price: 1164,
      stock: 991,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "229845319",
      description: "Aliquam erat volutpat.",
    },
    {
      name: "Dode Worden",
      heatLevel: 2,
      price: 182,
      stock: 891,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "102277151",
      description: "Suspendisse accumsan tortor quis turpis. Sed ante.",
    },
    {
      name: "Blake Linnitt",
      heatLevel: 7,
      price: 1867,
      stock: 431,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "026261698",
      description: "Fusce consequat.",
    },
    {
      name: "Vinita Etter",
      heatLevel: 6,
      price: 4043,
      stock: 218,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "599150273",
      description: "Cras pellentesque volutpat dui.",
    },
    {
      name: "Gerty Leversha",
      heatLevel: 9,
      price: 2222,
      stock: 531,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "228895055",
      description: "Suspendisse potenti. Nullam porttitor lacus at turpis.",
    },
    {
      name: "Valerie Coplestone",
      heatLevel: 4,
      price: 3543,
      stock: 292,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "328939715",
      description:
        "Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    },
    {
      name: "Vilma Sommerville",
      heatLevel: 3,
      price: 4317,
      stock: 381,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "237446441",
      description:
        "Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    },
    {
      name: "Sapphire Follett",
      heatLevel: 9,
      price: 2751,
      stock: 785,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "326252917",
      description: "Morbi non quam nec dui luctus rutrum. Nulla tellus.",
    },
    {
      name: "Tamma Clilverd",
      heatLevel: 1,
      price: 3641,
      stock: 809,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "284383818",
      description:
        "Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    },
    {
      name: "Randal Yeskov",
      heatLevel: 2,
      price: 826,
      stock: 930,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "375277585",
      description: "Aliquam non mauris.",
    },
    {
      name: "Nev Glowach",
      heatLevel: 7,
      price: 1225,
      stock: 755,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "246019164",
      description: "Praesent blandit.",
    },
    {
      name: "Ariella Frazer",
      heatLevel: 8,
      price: 290,
      stock: 276,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "813323308",
      description:
        "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.",
    },
    {
      name: "Atlanta Temby",
      heatLevel: 10,
      price: 3469,
      stock: 821,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "405096617",
      description:
        "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.",
    },
    {
      name: "Meredith Purchall",
      heatLevel: 7,
      price: 2045,
      stock: 292,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "818867182",
      description: "Mauris ullamcorper purus sit amet nulla.",
    },
    {
      name: "Ailsun West-Frimley",
      heatLevel: 10,
      price: 3740,
      stock: 133,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "640944756",
      description:
        "In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    },
    {
      name: "Laurene Ladewig",
      heatLevel: 4,
      price: 3604,
      stock: 753,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "435649463",
      description: "In sagittis dui vel nisl.",
    },
    {
      name: "Marleah Heggadon",
      heatLevel: 5,
      price: 2959,
      stock: 815,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "277457837",
      description: "Morbi a ipsum.",
    },
    {
      name: "Lexine Raisher",
      heatLevel: 3,
      price: 3138,
      stock: 849,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "415531203",
      description: "Nulla tellus. In sagittis dui vel nisl.",
    },
    {
      name: "Hi Klejna",
      heatLevel: 5,
      price: 1450,
      stock: 584,
      imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      sku: "073271617",
      description: "Donec semper sapien a libero. Nam dui.",
    },
    {
      name: "Sylvan Van der Hoven",
      heatLevel: 5,
      price: 1435,
      stock: 962,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "230181427",
      description:
        "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.",
    },
    {
      name: "Grayce Hallwood",
      heatLevel: 2,
      price: 1512,
      stock: 718,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "288513951",
      description:
        "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.",
    },
    {
      name: "Devi Dyke",
      heatLevel: 9,
      price: 1907,
      stock: 918,
      imageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      sku: "925796624",
      description: "Duis at velit eu est congue elementum.",
    },
    {
      name: "Rebecka Denidge",
      heatLevel: 6,
      price: 3410,
      stock: 135,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "299873322",
      description:
        "Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    },
    {
      name: "Bondon Helks",
      heatLevel: 1,
      price: 4255,
      stock: 791,
      imageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
      sku: "059404703",
      description:
        "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.",
    },
    {
      name: "Klarrisa Lovatt",
      heatLevel: 7,
      price: 434,
      stock: 957,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "264311828",
      description: "Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.",
    },
    {
      name: "Candace Giannoni",
      heatLevel: 3,
      price: 256,
      stock: 845,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "980712918",
      description: "Proin eu mi. Nulla ac enim.",
    },
    {
      name: "Morgen Falla",
      heatLevel: 7,
      price: 3050,
      stock: 351,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "613865687",
      description:
        "In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    },
    {
      name: "Nathanael Raatz",
      heatLevel: 5,
      price: 2401,
      stock: 605,
      imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      sku: "735265922",
      description:
        "Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.",
    },
  ])
);
